import { derivePropertyTsubo, type Property, type PropertyWithTsubo } from "@oceans-tenant/shared";

/**
 * Sanity 接続なしで開発・テストを進めるためのモックデータセット。
 * 実 Sanity 接続は Phase 3 の API レイヤで差し替える。
 *
 * 実在企業名・実在物件情報は含めない（CLAUDE.md 禁止事項）。
 */
const baseProperties: ReadonlyArray<Property> = [
  {
    title: "新宿三丁目 路面店（サンプル）",
    slug: "sample-shinjuku-sanchome-street",
    address: {
      prefecture: "東京都",
      city: "新宿区",
      streetAddress: "新宿 3-1-1",
      geopoint: { lat: 35.6921, lng: 139.7035 },
    },
    nearestStations: [
      { line: "東京メトロ丸ノ内線", station: "新宿三丁目", walkMinutes: 1 },
      { line: "JR 山手線", station: "新宿", walkMinutes: 6 },
    ],
    rent: 580000,
    commonFee: 28000,
    depositMonths: 10,
    keyMoneyMonths: 2,
    area: 38.4,
    floor: "1 階",
    buildingType: "street_level",
    condition: "skeleton",
    previousBusiness: "カフェ",
    suitableBusinessRefs: ["category-cafe", "category-bar"],
    images: [],
    description: "明治通り沿い、視認性の高いコーナー立地。スケルトン渡しで業態自由。",
    features: ["スケルトン", "天井高 3m", "視認性高"],
    availability: "public",
    listedByRef: "company-001",
    aiMeta: { aiExtracted: false },
    publishedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    title: "大阪市北区 ビルイン居抜き（サンプル）",
    slug: "sample-osaka-kitaku-second-hand",
    address: {
      prefecture: "大阪府",
      city: "大阪市北区",
      streetAddress: "梅田 1-2-3",
      geopoint: { lat: 34.7036, lng: 135.4995 },
    },
    nearestStations: [{ line: "Osaka Metro 御堂筋線", station: "梅田", walkMinutes: 3 }],
    rent: 320000,
    commonFee: 15000,
    depositMonths: 6,
    keyMoneyMonths: 1,
    area: 24.0,
    floor: "2 階",
    buildingType: "building_inline",
    condition: "second_hand",
    previousBusiness: "美容室",
    suitableBusinessRefs: ["category-beauty"],
    images: [],
    description: "梅田駅徒歩 3 分のビルイン物件。前テナント造作の一部を譲渡可能。",
    features: ["居抜き", "駅徒歩 5 分以内", "造作譲渡相談可"],
    availability: "negotiating",
    listedByRef: "company-002",
    aiMeta: { aiExtracted: true, aiConfidence: 0.86 },
    publishedAt: "2026-04-12T00:00:00.000Z",
  },
  {
    title: "福岡市中央区 路面（サンプル）",
    slug: "sample-fukuoka-chuoku-street",
    address: {
      prefecture: "福岡県",
      city: "福岡市中央区",
      streetAddress: "天神 2-3-4",
      geopoint: { lat: 33.5907, lng: 130.4017 },
    },
    nearestStations: [{ line: "福岡市営地下鉄空港線", station: "天神", walkMinutes: 2 }],
    rent: 220000,
    commonFee: 10000,
    depositMonths: 4,
    keyMoneyMonths: 0,
    area: 18.2,
    floor: "1 階",
    buildingType: "street_level",
    condition: "skeleton",
    suitableBusinessRefs: ["category-cafe", "category-retail"],
    images: [],
    description: "天神中心部、人通りの多い路面店舗。",
    features: ["スケルトン", "1 階路面", "視認性高"],
    availability: "public",
    listedByRef: "company-003",
    aiMeta: { aiExtracted: false },
    publishedAt: "2026-03-25T00:00:00.000Z",
  },
  {
    title: "渋谷区 地下バー区画（サンプル）",
    slug: "sample-shibuya-basement-bar",
    address: {
      prefecture: "東京都",
      city: "渋谷区",
      streetAddress: "宇田川町 5-6-7",
      geopoint: { lat: 35.6624, lng: 139.6986 },
    },
    nearestStations: [{ line: "JR 山手線", station: "渋谷", walkMinutes: 5 }],
    rent: 430000,
    commonFee: 21000,
    depositMonths: 8,
    keyMoneyMonths: 2,
    area: 33.0,
    floor: "B1",
    buildingType: "basement",
    condition: "transferable_fixtures",
    previousBusiness: "バー",
    suitableBusinessRefs: ["category-bar", "category-restaurant"],
    images: [],
    description: "深夜営業可、ダクト・グリストラップ完備の B1 区画。",
    features: ["深夜営業可", "ダクト有", "造作譲渡"],
    availability: "public",
    listedByRef: "company-001",
    aiMeta: { aiExtracted: true, aiConfidence: 0.71 },
    publishedAt: "2026-02-18T00:00:00.000Z",
  },
  {
    title: "港区 オフィス区画（サンプル）",
    slug: "sample-minatoku-office",
    address: {
      prefecture: "東京都",
      city: "港区",
      streetAddress: "六本木 7-8-9",
      geopoint: { lat: 35.6627, lng: 139.7322 },
    },
    nearestStations: [{ line: "東京メトロ日比谷線", station: "六本木", walkMinutes: 4 }],
    rent: 680000,
    commonFee: 34000,
    depositMonths: 12,
    keyMoneyMonths: 2,
    area: 56.8,
    floor: "5 階",
    buildingType: "second_floor_or_above",
    condition: "skeleton",
    suitableBusinessRefs: ["category-office"],
    images: [],
    description: "六本木駅徒歩 4 分、見晴らしの良い 5 階区画。",
    features: ["スケルトン", "電源 200V"],
    availability: "public",
    listedByRef: "company-002",
    aiMeta: { aiExtracted: false },
    publishedAt: "2026-01-30T00:00:00.000Z",
  },
];

export const MOCK_PROPERTIES: ReadonlyArray<PropertyWithTsubo> =
  baseProperties.map(derivePropertyTsubo);
